function sys = mylinearizemodel
% MYLINEARIZE Linearize the Simulink model - Motor.
%
% SYS = MYLINEARIZE linearizes the Simulink model Motor using
% the operating point defined by the model initial conditions.

% M-File generated by MATLAB(R) 7.8 and Simulink Control Design (TM) 2.5.
%
% Generated on: 03-Jan-2011 12:03:57

%% Specify the model name
model = 'Motor';

%% Create the linearization I/O as specified in Motor
ios(2) = linio('Motor/Elastic load 2',1,'out');
ios(1) = linio('Motor/Step',1,'in');

%% Linearize the model
sys = linearize(model,ios);

%% Plot the resulting linearization.
%step(sys)
bode(sys)